// Generated by scripts/analyze-deck.ts (100 bot games per cell). Do not edit by hand: change the deck or
// the modes and rerun it. Numbers come from random bots, so read them as estimates.
import type { GameMode } from './modes'

export interface DeckPlanRow {
  /** Cards in the deck for this table size. */
  deckSize: number
  /** Median number of turns in a game. */
  turns: number
  /** Average shots per player (drinks + penalty drinks; opening shot included). */
  shotsPerPlayer: number
  /** Average number of Last Call drink calls per game. */
  drinkCalls: number
}

export const DECK_PLAN: Partial<Record<GameMode, Record<number, DeckPlanRow>>> = {
  classic: {
    2: {
      deckSize: 60,
      turns: 7,
      shotsPerPlayer: 4.3,
      drinkCalls: 0
    },
    3: {
      deckSize: 68,
      turns: 34,
      shotsPerPlayer: 12.5,
      drinkCalls: 0
    },
    4: {
      deckSize: 96,
      turns: 30,
      shotsPerPlayer: 8.1,
      drinkCalls: 0
    },
    5: {
      deckSize: 116,
      turns: 36,
      shotsPerPlayer: 8.2,
      drinkCalls: 0
    },
    6: {
      deckSize: 128,
      turns: 46,
      shotsPerPlayer: 7.9,
      drinkCalls: 0
    },
    7: {
      deckSize: 152,
      turns: 48,
      shotsPerPlayer: 7.3,
      drinkCalls: 0
    },
    8: {
      deckSize: 160,
      turns: 53,
      shotsPerPlayer: 7,
      drinkCalls: 0
    },
    9: {
      deckSize: 176,
      turns: 56,
      shotsPerPlayer: 6.6,
      drinkCalls: 0
    },
    10: {
      deckSize: 176,
      turns: 56,
      shotsPerPlayer: 6,
      drinkCalls: 0
    }
  },
  party: {
    2: {
      deckSize: 60,
      turns: 9,
      shotsPerPlayer: 7.3,
      drinkCalls: 1.4
    },
    3: {
      deckSize: 76,
      turns: 32,
      shotsPerPlayer: 15.1,
      drinkCalls: 5.5
    },
    4: {
      deckSize: 108,
      turns: 37,
      shotsPerPlayer: 13.3,
      drinkCalls: 6.8
    },
    5: {
      deckSize: 132,
      turns: 39,
      shotsPerPlayer: 11.8,
      drinkCalls: 6.8
    },
    6: {
      deckSize: 160,
      turns: 54,
      shotsPerPlayer: 13.8,
      drinkCalls: 10.1
    },
    7: {
      deckSize: 172,
      turns: 56,
      shotsPerPlayer: 12.6,
      drinkCalls: 11.8
    },
    8: {
      deckSize: 192,
      turns: 59,
      shotsPerPlayer: 11.6,
      drinkCalls: 11.6
    },
    9: {
      deckSize: 212,
      turns: 62,
      shotsPerPlayer: 11.4,
      drinkCalls: 12.3
    },
    10: {
      deckSize: 208,
      turns: 64,
      shotsPerPlayer: 10.3,
      drinkCalls: 12.5
    }
  },
  rush: {
    2: {
      deckSize: 60,
      turns: 9,
      shotsPerPlayer: 7.3,
      drinkCalls: 1.4
    },
    3: {
      deckSize: 60,
      turns: 17,
      shotsPerPlayer: 8.5,
      drinkCalls: 2.6
    },
    4: {
      deckSize: 76,
      turns: 28,
      shotsPerPlayer: 10.9,
      drinkCalls: 4.6
    },
    5: {
      deckSize: 88,
      turns: 30,
      shotsPerPlayer: 10.4,
      drinkCalls: 6.4
    },
    6: {
      deckSize: 116,
      turns: 33,
      shotsPerPlayer: 9.7,
      drinkCalls: 6.6
    },
    7: {
      deckSize: 120,
      turns: 39,
      shotsPerPlayer: 9.9,
      drinkCalls: 7.9
    },
    8: {
      deckSize: 136,
      turns: 47,
      shotsPerPlayer: 9.3,
      drinkCalls: 7.4
    },
    9: {
      deckSize: 156,
      turns: 50,
      shotsPerPlayer: 9.6,
      drinkCalls: 10.1
    },
    10: {
      deckSize: 160,
      turns: 49,
      shotsPerPlayer: 8.6,
      drinkCalls: 9.1
    }
  },
  heavy: {
    2: {
      deckSize: 60,
      turns: 8,
      shotsPerPlayer: 7.5,
      drinkCalls: 2.4
    },
    3: {
      deckSize: 88,
      turns: 34,
      shotsPerPlayer: 18.2,
      drinkCalls: 11.5
    },
    4: {
      deckSize: 116,
      turns: 40,
      shotsPerPlayer: 16.6,
      drinkCalls: 15.1
    },
    5: {
      deckSize: 152,
      turns: 48,
      shotsPerPlayer: 15.4,
      drinkCalls: 15.4
    },
    6: {
      deckSize: 168,
      turns: 56,
      shotsPerPlayer: 15.1,
      drinkCalls: 18.7
    },
    7: {
      deckSize: 180,
      turns: 69,
      shotsPerPlayer: 17,
      drinkCalls: 25.6
    },
    8: {
      deckSize: 212,
      turns: 67,
      shotsPerPlayer: 14.1,
      drinkCalls: 23.4
    },
    9: {
      deckSize: 228,
      turns: 74,
      shotsPerPlayer: 14,
      drinkCalls: 26.1
    },
    10: {
      deckSize: 232,
      turns: 64,
      shotsPerPlayer: 12,
      drinkCalls: 24.1
    }
  },
  hardcore: {
    2: {
      deckSize: 60,
      turns: 11,
      shotsPerPlayer: 10.4,
      drinkCalls: 3.8
    },
    3: {
      deckSize: 100,
      turns: 47,
      shotsPerPlayer: 28.9,
      drinkCalls: 22.7
    },
    4: {
      deckSize: 144,
      turns: 50,
      shotsPerPlayer: 23.3,
      drinkCalls: 21.7
    },
    5: {
      deckSize: 180,
      turns: 60,
      shotsPerPlayer: 22.2,
      drinkCalls: 25.4
    },
    6: {
      deckSize: 204,
      turns: 80,
      shotsPerPlayer: 24.2,
      drinkCalls: 34.1
    },
    7: {
      deckSize: 224,
      turns: 85,
      shotsPerPlayer: 21.8,
      drinkCalls: 38.2
    },
    8: {
      deckSize: 248,
      turns: 87,
      shotsPerPlayer: 20.9,
      drinkCalls: 39.7
    },
    9: {
      deckSize: 260,
      turns: 90,
      shotsPerPlayer: 18.4,
      drinkCalls: 38.9
    },
    10: {
      deckSize: 284,
      turns: 102,
      shotsPerPlayer: 19.8,
      drinkCalls: 46.2
    }
  }
}
