// Generated by scripts/analyze-deck.ts (150 bot games per cell). Do not edit by hand: change the deck or
// the modes and rerun it. Numbers come from random bots, so read them as estimates.
import type { GameMode } from './modes'

export interface DeckPlanRow {
  /** Cards in the deck for this table size. */
  deckSize: number
  /** Median number of turns in a game. */
  turns: number
  /** Average shots per player (drinks + penalty drinks; opening shot included). */
  shotsPerPlayer: number
  /** Average number of Last Call drink calls per game. */
  drinkCalls: number
}

export const DECK_PLAN: Partial<Record<GameMode, Record<number, DeckPlanRow>>> = {
  classic: {
    2: {
      deckSize: 60,
      turns: 7,
      shotsPerPlayer: 4.5,
      drinkCalls: 0
    },
    3: {
      deckSize: 68,
      turns: 32,
      shotsPerPlayer: 12.2,
      drinkCalls: 0
    },
    4: {
      deckSize: 96,
      turns: 31,
      shotsPerPlayer: 8.2,
      drinkCalls: 0
    },
    5: {
      deckSize: 116,
      turns: 37,
      shotsPerPlayer: 8.3,
      drinkCalls: 0
    },
    6: {
      deckSize: 132,
      turns: 47,
      shotsPerPlayer: 8.6,
      drinkCalls: 0
    }
  },
  party: {
    2: {
      deckSize: 60,
      turns: 9,
      shotsPerPlayer: 7,
      drinkCalls: 1.3
    },
    3: {
      deckSize: 76,
      turns: 31,
      shotsPerPlayer: 15,
      drinkCalls: 5.5
    },
    4: {
      deckSize: 104,
      turns: 34,
      shotsPerPlayer: 13.1,
      drinkCalls: 6.6
    },
    5: {
      deckSize: 132,
      turns: 40,
      shotsPerPlayer: 11.9,
      drinkCalls: 6.8
    },
    6: {
      deckSize: 156,
      turns: 50,
      shotsPerPlayer: 12.5,
      drinkCalls: 9.2
    }
  },
  rush: {
    2: {
      deckSize: 60,
      turns: 9,
      shotsPerPlayer: 7,
      drinkCalls: 1.3
    },
    3: {
      deckSize: 60,
      turns: 17,
      shotsPerPlayer: 8.8,
      drinkCalls: 2.6
    },
    4: {
      deckSize: 76,
      turns: 27,
      shotsPerPlayer: 10.6,
      drinkCalls: 4.4
    },
    5: {
      deckSize: 92,
      turns: 30,
      shotsPerPlayer: 10,
      drinkCalls: 7
    },
    6: {
      deckSize: 112,
      turns: 36,
      shotsPerPlayer: 9.7,
      drinkCalls: 6.6
    }
  },
  heavy: {
    2: {
      deckSize: 60,
      turns: 8,
      shotsPerPlayer: 7.3,
      drinkCalls: 2.3
    },
    3: {
      deckSize: 92,
      turns: 39,
      shotsPerPlayer: 20.6,
      drinkCalls: 14.5
    },
    4: {
      deckSize: 116,
      turns: 40,
      shotsPerPlayer: 16.9,
      drinkCalls: 15
    },
    5: {
      deckSize: 152,
      turns: 45,
      shotsPerPlayer: 15.3,
      drinkCalls: 15.3
    },
    6: {
      deckSize: 168,
      turns: 56,
      shotsPerPlayer: 15.1,
      drinkCalls: 18.5
    }
  },
  hardcore: {
    2: {
      deckSize: 60,
      turns: 11,
      shotsPerPlayer: 10.5,
      drinkCalls: 3.9
    },
    3: {
      deckSize: 72,
      turns: 25,
      shotsPerPlayer: 15.9,
      drinkCalls: 10.8
    },
    4: {
      deckSize: 92,
      turns: 35,
      shotsPerPlayer: 17.2,
      drinkCalls: 15.6
    },
    5: {
      deckSize: 120,
      turns: 36,
      shotsPerPlayer: 15.6,
      drinkCalls: 18.2
    },
    6: {
      deckSize: 144,
      turns: 47,
      shotsPerPlayer: 16,
      drinkCalls: 20.7
    }
  }
}
