// How many cards should a table of N players use, per mode? Writes packages/cards/src/deck-plan.ts.
//   npx tsx scripts/analyze-deck.ts [gamesPerCell]
//
// Method: random bots play many games per (mode, players). We count the cards a game actually uses
// (starting hands + every draw, Incidents included) and size the deck to the median of that, so a
// typical game goes through the deck about once: every card gets its chance and drink calls show up
// at the rate the mode intends. Never below 60 cards (enough for one copy of every card type).
// A second run with the resized deck measures what the lobby shows (turns, shots, drink calls).
// Bots are not people: treat the numbers as estimates.
import { writeFileSync } from 'node:fs'
import { createGame, dispatch } from '../packages/engine/src'
import type { CardDef, GameConfig } from '../packages/engine/src'
import { nextRandomMove } from '../packages/engine/test/random-player'
import { MODES, modeDeck, resizeDeck, tableConfig } from '../packages/cards/src/modes'

const GAMES = Number(process.argv[2] ?? 150)
const MIN_DECK = 60
const NAMES = ['a', 'b', 'c', 'd', 'e', 'f']

interface Result {
  cardsUsed: number
  turns: number
  shots: number
  drinkCalls: number
}

function play(cards: CardDef[], config: Partial<GameConfig>, players: number, seed: number): Result | null {
  let s = createGame({
    players: NAMES.slice(0, players).map((id) => ({ id, name: id, avatar: 'a' })),
    cards,
    config,
    seed: `plan-${seed}`
  })
  const rng = { rng: seed * 7919 + 13 }
  let cardsUsed = players * s.config.startHand
  let drinkCalls = 0
  let actionsThisTurn = 0
  let lastTurn = s.turnNumber
  for (let i = 0; i < 8000 && !s.finished; i++) {
    if (s.turnNumber !== lastTurn) (lastTurn = s.turnNumber), (actionsThisTurn = 0)
    const move = nextRandomMove(s, rng, actionsThisTurn)
    let r = dispatch(s, move.playerId, move.action)
    actionsThisTurn++
    if (!r.ok) {
      r = dispatch(s, s.activeId, { type: 'finish_turn' })
      if (!r.ok && s.pending?.kind === 'response') r = dispatch(s, s.pending.eligible[0], { type: 'pass_response' })
      if (!r.ok) continue
    }
    for (const fx of r.fx) {
      if (fx.kind === 'draw' || fx.kind === 'event') cardsUsed++
      if (fx.kind === 'interlude' && fx.mode === 'drinkcall') drinkCalls++
    }
    s = r.state
  }
  if (!s.finished) return null
  const shots = s.players.reduce((n, p) => n + p.potionsDrunk, 0) / players
  return { cardsUsed, turns: s.turnNumber, shots, drinkCalls }
}

const median = (xs: number[]) => [...xs].sort((a, b) => a - b)[Math.floor(xs.length / 2)]
const mean = (xs: number[]) => xs.reduce((a, b) => a + b, 0) / xs.length
const round1 = (x: number) => Math.round(x * 10) / 10

function run(cards: CardDef[], config: Partial<GameConfig>, players: number): Result[] {
  return Array.from({ length: GAMES }, (_, i) => play(cards, config, players, i + 1)).filter((r): r is Result => !!r)
}

const plan: Record<string, Record<number, object>> = {}
for (const mode of MODES) {
  plan[mode.id] = {}
  const full = modeDeck(mode.id)
  for (let players = 2; players <= 6; players++) {
    const config = tableConfig(mode.id, players)
    const first = run(full, config, players)
    const deckSize = Math.max(MIN_DECK, Math.round(median(first.map((r) => r.cardsUsed)) / 4) * 4)
    const second = run(resizeDeck(full, deckSize), config, players)
    const row = {
      deckSize,
      turns: median(second.map((r) => r.turns)),
      shotsPerPlayer: round1(mean(second.map((r) => r.shots))),
      drinkCalls: round1(mean(second.map((r) => r.drinkCalls)))
    }
    plan[mode.id][players] = row
    console.log(`${mode.id.padEnd(8)} ${players}p  used ~${median(first.map((r) => r.cardsUsed))}  ->`, JSON.stringify(row))
  }
}

const body = JSON.stringify(plan, null, 2).replace(/"(\w+)":/g, '$1:').replace(/"/g, "'")
writeFileSync(
  new URL('../packages/cards/src/deck-plan.ts', import.meta.url),
  `// Generated by scripts/analyze-deck.ts (${GAMES} bot games per cell). Do not edit by hand: change the deck or
// the modes and rerun it. Numbers come from random bots, so read them as estimates.
import type { GameMode } from './modes'

export interface DeckPlanRow {
  /** Cards in the deck for this table size. */
  deckSize: number
  /** Median number of turns in a game. */
  turns: number
  /** Average shots per player (drinks + penalty drinks; opening shot included). */
  shotsPerPlayer: number
  /** Average number of Last Call drink calls per game. */
  drinkCalls: number
}

export const DECK_PLAN: Partial<Record<GameMode, Record<number, DeckPlanRow>>> = ${body}
`
)
console.log('wrote packages/cards/src/deck-plan.ts')
