// Builds apps/web/app/theme/icon-data.ts: the game-style SVG icons the game uses, copied out of the
// open-source game-icons.net set (CC BY 3.0, via @iconify-json/game-icons). Run after changing the list:
//   node scripts/build-icons.mjs
// Only the icons listed here end up in the web bundle, and nothing is fetched at runtime.
import { readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'

const require = createRequire(import.meta.url)
const set = JSON.parse(readFileSync(require.resolve('@iconify-json/game-icons/icons.json'), 'utf8'))

/** our name -> game-icons name */
const ICONS = {
  // HUD and actions
  hp: 'techno-heart',
  shot: 'glass-shot',
  cards: 'card-draw',
  rebase: 'card-exchange',
  backlog: 'book-pile',
  trash: 'trash-can',
  drink: 'glass-celebration',
  endturn: 'clockwise-rotation',
  menu: 'hamburger-menu',
  crown: 'crown',
  trophy: 'laurels-trophy',
  sparkles: 'sparkles',
  alarm: 'ringing-alarm',
  skull: 'death-skull',
  sober: 'water-drop',
  exit: 'exit-door',
  turn: 'player-next',
  rules: 'secret-book',
  log: 'scroll-unfurled',
  music: 'musical-notes',
  sound: 'speaker',
  mute: 'speaker-off',
  copy: 'folded-paper',
  link: 'linked-rings',
  ready: 'check-mark',
  play: 'play-button',
  // elements
  hotfix: 'fire',
  freeze: 'snowflake-1',
  deploy: 'lightning-helix',
  // card types
  attack: 'crossed-swords',
  defend: 'bordered-shield',
  support: 'health-increase',
  curse: 'daemon-skull',
  artifact: 'crystal-shine',
  incident: 'siren',
  // avatars
  'av-frontend': 'paint-brush',
  'av-backend': 'cog',
  'av-devops': 'spanner',
  'av-qa': 'ladybug',
  'av-pm': 'notebook',
  'av-designer': 'pencil-ruler',
  'av-junior': 'egg-clutch',
  'av-senior': 'wizard-face',
  // one picture per card
  'quick-patch': 'bandage-roll',
  'merge-conflict': 'branch-arrow',
  'null-pointer': 'ghost',
  segfault: 'spiky-explosion',
  'prod-fire': 'fire-bomb',
  'sudo-rm-rf': 'nuclear',
  'code-freeze': 'frozen-block',
  'dependency-lock': 'dial-padlock',
  'cold-start': 'power-button',
  'rate-limit': 'speedometer',
  deadlock: 'crossed-chains',
  'friday-deploy': 'rocket',
  'pipeline-surge': 'heavy-lightning',
  'hot-reload': 'recycle',
  'load-test': 'weight-lifting-up',
  'try-catch': 'fishing-net',
  rollback: 'anticlockwise-rotation',
  firewall: 'brick-wall',
  'code-review': 'magnifying-glass',
  'feature-flag': 'flying-flag',
  'force-push': 'mailed-fist',
  copilot: 'robot-antennas',
  'rubber-duck': 'plastic-duck',
  'pair-programming': 'team-idea',
  'context-switch': 'body-swapping',
  'happy-hour': 'beer-stein',
  'google-it': 'spyglass',
  refactor: 'broom',
  'standup-meeting': 'conversation',
  'memory-leak': 'droplet-splash',
  'technical-debt': 'pay-money',
  'scope-creep': 'expander',
  'three-hour-meeting': 'hourglass',
  'legacy-code': 'papyrus',
  'imposter-syndrome': 'drama-masks',
  'spilled-coffee': 'coffee-cup',
  'mechanical-keyboard': 'keyboard',
  'ultrawide-monitor': 'tv',
  'gaming-chair': 'office-chair',
  'senior-badge': 'ribbon-medal',
  'prod-down': 'server-rack',
  'critical-incident': 'burning-skull',
  'free-pizza': 'pizza-slice',
  'requirement-change': 'scroll-quill',
  'team-building': 'party-popper',
  'freeze-week': 'snowflake-2',
  'server-migration': 'truck',
  'bug-bash': 'spotted-bug',
  // house-rule cards (H3)
  'coffee-break': 'coffee-mug',
  hackathon: 'rolling-dices',
  pause: 'hourglass'
}

const missing = Object.entries(ICONS).filter(([, gi]) => !set.icons[gi])
if (missing.length) {
  console.error('Missing icons:', missing.map(([ours, gi]) => `${ours} -> ${gi}`).join(', '))
  process.exit(1)
}

// drop the hard-coded fill so the icon takes its colour (or gradient) from CSS
const clean = (body) => body.replace(/ fill="currentColor"/g, '')
const lines = Object.entries(ICONS).map(([ours, gi]) => `  ${JSON.stringify(ours)}: ${JSON.stringify(clean(set.icons[gi].body))}`)

writeFileSync(
  new URL('../apps/web/app/theme/icon-data.ts', import.meta.url),
  `// GENERATED by scripts/build-icons.mjs: do not edit by hand.
// Icons from game-icons.net (Lorc, Delapouite & contributors), licensed CC BY 3.0 (https://creativecommons.org/licenses/by/3.0/).
// All icons use a 512x512 viewBox.
export const ICON_CREDIT = 'Icons: game-icons.net by Lorc, Delapouite & contributors (CC BY 3.0)'

export const iconData: Record<string, string> = {
${lines.join(',\n')}
}
`
)
console.log(`wrote ${lines.length} icons`)
